# Generated by Django 3.1.7 on 2022-03-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_characteristicproduct_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desciption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
