# Generated by Django 3.1.7 on 2022-03-30 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_desciption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desciption',
            new_name='description',
        ),
    ]
