# Generated by Django 3.1.7 on 2022-05-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20220517_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_issued',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
